### ISSUE TITLE
Create custom consumption pattern

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqnext#11]
":I know the pattern of my appliance in watts. Maybe an option for a custom pattern would be possible. To make the calculation of the price more accurate."

_Originally posted by @sjoukebakker in https://github.com/elden1337/hass-peaqnext/issues/5#issuecomment-1663492397_

**Comment by elden1337** [comment]
@sjoukebakker can you post an example of this consumption pattern?

**Comment by sjoukebakker** [comment]
Well to be honest, I only have the data from my plug. Which looks like this:
![afbeelding](https://github.com/elden1337/hass-peaqnext/assets/50876518/1abdf044-6323-42a6-90f1-88c2ddf56fb4)

But I could somehow try to convert it to a profile like in this example (watts per 15 minutes): 
```
		self.timestep = 900 
		
		# Profiles in Watts
		# Vaatwasser = 1.3kWh
		self.profile = [200, 1704, 1139, 66, 44, 1592, 462, 4, 5]
```
I found this in GENETX's code: https://github.com/GENETX/homeassistant/blob/master/appdaemon/apps/vaatwasser.py#L29C10-L29C10

**Comment by elden1337** [comment]
Oh what kind of repo is that? Looks like a similar one

**Comment by elden1337** [comment]
And yeah i would convert it to percent of total energy in the steps later.

**Comment by elden1337** [comment]
handled in https://github.com/elden1337/hass-peaqnext/releases/tag/v0.4.0
