### ISSUE TITLE
Make comparer round to two decimals

### ISSUE THREAD

**Issue by sjoukebakker** [elden1337/hass-peaqnext#13]
These quotes are from #5 
> Rounding to one decimal makes the data quite useless in my case because that allows a difference of 0.09 EUR (1.05 SEK) . My hourly prices are also in that range today (cheapest hour is 0.285 and most expensive 0.377). So in my case it basically sorts by hour right now.

> I think the comparer perhaps could be improved by adding one decimal if using cent. Lets look in another issue

We also have the `Closest cheap hour limit` option to limit the amount of time from now to the next cheapest option. So maybe it would be fine to just sort by two decimals all the time. However I understand that that is very little money in SEK. 😅

It could also be some kind of calculation based on the available prices. A percentage of the difference between the highest and lowest value.

**Comment by elden1337** [comment]
it will be a special case for EUR currency. all the others in nordpool are fine with the current comparer (and it works as intended with a short comparer for those, otherwise it's never equal)
