### ISSUE TITLE
Remove current hour

### ISSUE THREAD

**Issue by sjoukebakker** [elden1337/hass-peaqnext#14]
Maybe the current hour can also be removed from the list. Now it will display starting at 10:00 as the cheapest option, even when it is already 10:59.

_Originally posted by @sjoukebakker in https://github.com/elden1337/hass-peaqnext/issues/5#issuecomment-1665261136_

**Comment by elden1337** [comment]
What if state was gliding from now > if current hour would be best within range, but keep the attributes list steady? That way recorder (HA-db) would be less spammed.

**Comment by elden1337** [comment]
will be resolved together with #12
