### ISSUE TITLE
Alternative to NORDPOOL

### ISSUE THREAD

**Issue by Hoekeren** [elden1337/hass-peaqnext#15]
Hi thanks for the great work. 
Is it possible to use another source than NORDPOOL? 
I use https://github.com/MTrab/energidataservice (that is build ond the data from NORPOOL, adding local gridcosts) it would be great if instaed of the "raw" price from Nordpool, I would get the expected cost that would more closely match me electricity bill.
I thank you in advance.
Kind regard 
Christian

**Comment by elden1337** [comment]
Ofc ill have a look! Can i count on you testing it out if i get around to do it? Since i dont have that source myself.

**Comment by Hoekeren** [comment]
I will be happy to contribute with testing

**Comment by elden1337** [comment]
it will not be a selection but a winner-loop where energidataservice will be initialized if found, otherwise it will try with nordpool. 
the energidataservice does not have any exposed attribute for `price_in_cent` so I can't have that set. Either I'll PR to that repo or someone else does it, but just so that you know.

**Comment by Hoekeren** [comment]
Sound great Magnus. I know that Marlene Trab who is behind energidataservice is very skilled and engaged in developing solutions for Homeassistant, so I am fairly confident that she can and will assist if her time allows it. Thank you for your great workMed venlig hilsenChristian

**Comment by elden1337** [comment]
@Hoekeren please download this beta-release (you may need to tweak your hacs to see betas) and report here what you find. I'll await your comment before merging it into the main-code:

https://github.com/elden1337/hass-peaqnext/releases/tag/v0.4.0i15b0

**Comment by Hoekeren** [comment]
Hi Magnus.I removed my sensors and peaqnext from HA. Found your beta and downloaded it.Restarted HA.Tried to add the integration - but it is not available in the list?Have I done anything wrong?Med venlig hilsenChristianFra: Magnus Eldén ***@***.***>Sendt: søndag, august 13, 2023 10:10:38 PMTil: elden1337/hass-peaqnext ***@***.***>Cc: Hoekeren ***@***.***>; Assign ***@***.***>Emne: Re: [elden1337/hass-peaqnext] Alternative to NORDPOOL (Issue #15)
Assigned #15 to @Hoekeren.

**Comment by elden1337** [comment]
Nope. My mistake. Seems HA cannot use such long version numbers (0.4.0i15b0). Was not aware of that. 

If you have access to file editor you can edit custom_components/peaqnext/manifest.json and change the version to just "0.4.0b0"

Otherwise i'll re-release tonight.

**Comment by Hoekeren** [comment]
I will try that right now.Med venlig hilsenChristian

**Comment by Hoekeren** [comment]
Hi Magnus.I am back from testing. It does not seem to work. The sensors still reflect to nordpool prices.Pictures show the nordpool sensor and a graph showing prices from "energidataservice" obove peaqnextsensors. "Vasketid" uses 1KwH. Opvasketid uses 1,5KwHMed venlig hilsenChristianFra: Christian Skallerup-Børgesen ***@***.***>Sendt: mandag, august 14, 2023 3:13:09 PMTil: elden1337/hass-peaqnext ***@***.***>; elden1337/hass-peaqnext ***@***.***>Cc: Mention ***@***.***>Emne: Re: [elden1337/hass-peaqnext] Alternative to NORDPOOL (Issue #15)I will try that right now.Med venlig hilsenChristian

**Comment by Hoekeren** [comment]
I have removed nordpool and made new sensors. Tha resultat i this error.Logger: homeassistant.config_entriesSource: helpers/event.py:194First occurred: 15.34.46 (12 occurrences)Last logged: 15.51.03Error setting up entry Peaqnext-sensors for peaqnextTraceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup    result = await component.async_setup_entry(hass, self)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/config/custom_components/peaqnext/__init__.py", line 21, in async_setup_entry    hub = Hub(hass)          ^^^^^^^^^  File "/config/custom_components/peaqnext/service/hub.py", line 30, in __init__    async_track_state_change(  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 194, in async_track_state_change    entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 194, in <genexpr>    entity_ids = tuple(entity_id.lower() for entity_id in entity_ids)                       ^^^^^^^^^^^^^^^AttributeError: 'NoneType' object has no attribute 'lower'Med venlig hilsenChristian

**Comment by Hoekeren** [comment]
And this oneDenne fejl stammer fra en brugerdefineret integration.Logger: custom_components.peaqnext.service.spotprice.ispotpriceSource: custom_components/peaqnext/service/spotprice/ispotprice.py:26Integration: peaqnext, utility sensors (documentation, issues)First occurred: 15.34.46 (12 occurrences)Last logged: 15.51.03I was unable to get a Spotprice-entity. Cannot continue.: no entities found for Spotprice.Med venlig hilsenChristian

**Comment by elden1337** [comment]
Hmm clearly forgot something. 
You have one (just one) sensor for energi...?

**Comment by Hoekeren** [comment]
👍💪 I will gladly test more if necessary 😉Med venlig hilsenChristian

**Comment by elden1337** [comment]
ok  @Hoekeren this version worked on my machine: https://github.com/elden1337/hass-peaqnext/releases/tag/v0.4.0b151

Please review the prices and see if they are sane or needs recalculation.

**Comment by Hoekeren** [comment]
Work great on my side aswell. Thank you for the great work.Med venlig hilsenChristian

**Comment by elden1337** [comment]
splendid. letting issue sit open til i've released it in a stable version.

**Comment by elden1337** [comment]
Handled in https://github.com/elden1337/hass-peaqnext/releases/tag/v0.4.0. Reopen issue if not working.
