### ISSUE TITLE
Feature request: Add "price_subtract" config option

### ISSUE THREAD

**Issue by SkywiperSolutions** [elden1337/hass-peaqnext#22]
In Denmark, there's an option to get a refund of the tax paid per kWh to charge EV vehicles. This means that a peaqnext device used for EV charging should subtract a specific amount per kWh.
Would you consider adding an optional configuration option called something like "price_subtract" that defaults to "0" and is subtracted the Nordpool values?

**Comment by elden1337** [comment]
Handled in https://github.com/elden1337/hass-peaqnext/releases/tag/v0.4.0. Reopen issue if not working.
