### ISSUE TITLE
Calc issue

### ISSUE THREAD

**Issue by thommicom** [elden1337/hass-peaqnext#31]
I have setup a sensor but the results are totally wrong. Its set up to 12h but pulls 24h. 

The Price is far away from reality. (I konw hard times, buts thats a bit too much ;) ) Also the foreseen cheapest time issnt the cheapest.

Any idea?

[sensor.peaqnext_battload1h](https:/xxxxxx.duckdns.org/developer-tools/state#)
PeaqNext battload1h
23:00-00:00⁺¹ € 0.35	All sequences: 
23:00⁺¹-00:00⁺¹: € 0.33
23:00-00:00⁺¹: € 0.35
00:00⁺¹-01:00⁺¹: € 0.36
01:00⁺¹-02:00⁺¹: € 0.36
02:00⁺¹-03:00⁺¹: € 0.36
03:00⁺¹-04:00⁺¹: € 0.36
04:00⁺¹-05:00⁺¹: € 0.36
'>> 22:00-23:00': € 0.37
12:00⁺¹-13:00⁺¹: € 0.37
13:00⁺¹-14:00⁺¹: € 0.37
21:00⁺¹-22:00⁺¹: € 0.37
05:00⁺¹-06:00⁺¹: € 0.38
11:00⁺¹-12:00⁺¹: € 0.39
14:00⁺¹-15:00⁺¹: € 0.39
22:00⁺¹-23:00⁺¹: € 0.39
10:00⁺¹-11:00⁺¹: € 0.46
15:00⁺¹-16:00⁺¹: € 0.46
20:00⁺¹-21:00⁺¹: € 0.46
16:00⁺¹-17:00⁺¹: € 0.5
06:00⁺¹-07:00⁺¹: € 0.51
09:00⁺¹-10:00⁺¹: € 0.55
17:00⁺¹-18:00⁺¹: € 0.56
19:00⁺¹-20:00⁺¹: € 0.56
18:00⁺¹-19:00⁺¹: € 0.59
07:00⁺¹-08:00⁺¹: € 0.64
08:00⁺¹-09:00⁺¹: € 0.71

Consumption type: Flat consumption
Duration in minutes: 60
Consumption in kWh: 3.6
Closest cheap hour limit: 12.0h
raw_start: 2023-10-22T23:00:00.000000
price_source: Nordpool
update_by: Every hour
calculate_by: Start time
icon: mdi:clock-start
friendly_name: PeaqNext battload1h

**Comment by elden1337** [comment]
Hi. What was the underlying pricedata for this result? Can you provide me with the two lists per day and ill run some tests to see.

**Comment by elden1337** [comment]
Not 10.2 eurocents between 22-23 then?

**Comment by elden1337** [comment]
also, as per the readme, the closest cheap hour limit does not mean that you will not see prices more than x hrs in the future as calculations:

```
Closest cheap hour - (optional, defaults to 12h) Change the suggested "cheapest price within x hours" as sensor-state. Set to 48 or more to ignore it.
```

in your list, the cheapest withing 12hrs which is your limitation set is the one currently stated as state (23-00@0.35€)

**Comment by thommicom** [comment]
Damn. My mistake. I missed the fact, that the calculated result also includes the factor 3.6 for 3.6kwh. Stupid me. Sorry!
Looks like It was a bit too late for me yesterday. :(
Please close the ticket.
