### ISSUE TITLE
Excluded hours not honored

### ISSUE THREAD

**Issue by tux2000** [elden1337/hass-peaqnext#8]
Added a new sensor with this configuration:
![2023-07-31_17-01](https://github.com/elden1337/hass-peaqnext/assets/1639672/528c91fd-d600-422f-b26c-378429ace49c)

Got this status:
![image](https://github.com/elden1337/hass-peaqnext/assets/1639672/02c61a8a-9e18-437b-b169-2d7bd6df6409)

Hours 3 and 4 should neither be starting or ending hours...

peaqnext version: v.0.1.2

**Comment by elden1337** [comment]
hopefully better now in 0.1.3

**Comment by tux2000** [comment]
Still not working as expected:
![image](https://github.com/elden1337/hass-peaqnext/assets/1639672/d1b944a6-307e-4d99-ac1c-c44a519aee63)
(some config as above...)

**Comment by elden1337** [comment]
I don't see any nonhours in this image being set.

**Comment by elden1337** [comment]
![image](https://github.com/elden1337/hass-peaqnext/assets/22585518/ed95ebcb-1a99-41f0-a362-1f1dfd8aa7e3)

Works here (just end hours though). 
U never see these on the attributes?

**Comment by tux2000** [comment]
Nope, Non hours dont show up in the attributes when I make a new sensor :(

**Comment by elden1337** [comment]
Ok, referenced as new issue. Away til tomorrow so bare with me til then at the earliest.
